config/routes.rb
Rails.application.routes.draw do

  resources :idea_response_comments

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => 'users/registrations'}

  resources :response_requests

  root to: 'home#splash'

  get 'home/splash'
  get 'home/about'
  get 'home/contact'
  get 'error/needResponseRequests'

  resources :idea_responses

  resources :ideas
  get 'ideas/idea_wall'

end

app/models/idea.rb
class Idea < ActiveRecord::Base

  attr_accessor :responseRequestsPending
  attr_accessor :responses

  has_one :user

  def getUser()
    return User.find(userId)
  end

  def self.getIdeasByUser(user)
    ideas = Idea.where "userId = ?", user.id

    for idea in ideas
      idea.responseRequestsPending = ResponseRequest.where("ideaId = ?", idea.id).count()
    end

    return ideas
  end

  def createInitialResponseRequest(user)
    @response_request = ResponseRequest.new
    @response_request.ideaId = id
    @response_request.save

    user.addIdeaAmmo(-1, user)
  end

  def getResponses()
    idea_responses = IdeaResponse.where("ideaId = ?", id).order(created_at: :asc)
    idea_responses.map{|idea_response| idea_response.comments = idea_response.get_comments()}
    return idea_responses
  end
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  before_action :set_idea, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_filter :only_allow_user, only: [:edit, :update, :destroy]

  def only_allow_user
    if current_user.id != @idea.userId
      redirect_to ideas_path
    end
  end

  # GET /ideas
  # GET /ideas.json
  def index
    @get_all_users = params[:all_users]

    if @get_all_users == '0'
      @ideas = Idea.getIdeasByUser(current_user)
    else
      @ideas = Idea.all.limit(20).order(created_at: :desc)
      render 'ideas/idea_wall'
    end

  end

  # GET /ideas/1
  # GET /ideas/1.json
  def show
    @idea_responses = @idea.getResponses()
  end

  # GET /ideas/new
  def new
    @idea = Idea.new
  end

  # GET /ideas/1/edit
  def edit
    @idea_responses = @idea.getResponses()
  end

  # POST /ideas
  # POST /ideas.json
  def create
    @idea = Idea.new(idea_params)
    @idea.userId = current_user.id

    respond_to do |format|
      if @idea.save
        #format.html { redirect_to @idea, notice: 'Idea was successfully created.' }
        format.html { redirect_to ideas_path, notice: 'Idea was successfully created.' }
        format.json { render :show, status: :created, location: @idea }
        
        @idea.createInitialResponseRequest(current_user)

      else
        format.html { render :new }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ideas/1
  # PATCH/PUT /ideas/1.json
  def update
    respond_to do |format|
      if @idea.update(idea_params)
        format.html { redirect_to @idea, notice: 'Idea was successfully updated.' }
        format.json { render :show, status: :ok, location: @idea }
      else
        format.html { render :edit }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ideas/1
  # DELETE /ideas/1.json
  def destroy
    @idea.destroy

    #destroy all idea responses, response requests (with refund), comments
    @idea_responses = IdeaResponse.where('ideaId = ?', @idea.id)
    @response_requests = ResponseRequest.where('ideaId = ?', @idea.id)

    current_user.ideaAmmo += @response_requests.count
    current_user.save

    @idea_responses.each do |idea_response|
      comments = idea_response.get_comments()
      comments.each{|comment| comment.destroy}
      idea_response.destroy
    end

    @response_requests.each{ |response_request| response_request.destroy}

    respond_to do |format|
      format.html { redirect_to ideas_url, notice: 'Idea was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_idea
    @idea = Idea.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def idea_params
    params.require(:idea).permit(:title, :description, :userId)
  end
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/views/ideas/_form.html.erb
<%= form_for(@idea, html: {'data-parsley-validate' => ''}) do |f| %>
<div class="form-group">
  <% if @idea.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@idea.errors.count, "error") %> prohibited this idea from being saved:</h2>

      <ul>
      <% @idea.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: 'form-control' %>
  </div>
  <div class="field">
    <%= f.label :description %><a href='http://daringfireball.net/projects/markdown/syntax'> (You can use Markdown)</a><br>
    <%= f.text_area :description, 'data-parsley-validation-threshold' => "0", 'data-parsley-trigger' => "keyup", 'data-parsley-minlength' => 100, class: 'form-control', rows: 5 %>
  </div>

  <div class="actions">
    <% if action_name == 'new' %>
      <%= f.submit "Post Idea", class: 'btn btn-primary' %>
    <% else %>
      <%= f.submit "Update", class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>
<% end %>

app/views/ideas/_idea.html.erb
<p>
<h2>
  <%= @idea.title %>
</h2>
</p>
<div style='text-align:left' class="well">
  <%= $markdown.render(@idea.description).html_safe %>
</div>
<% if current_user.id == @idea.userId %>
  <%= link_to 'Edit', edit_idea_path(@idea), class: 'btn btn-primary' %>
  <%= link_to 'Delete', @idea, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-primary' %>
  <br />
<br />
<p>Created <%= time_ago_in_words(@idea.created_at) %> ago by user #<%= @idea.userId %></p>
<% end %>

app/views/ideas/edit.html.erb
<h1>Editing Startup Idea</h1>
<div class="container">
  <div class="row">
    <div class="content-div col-md-8 col-md-offset-2">
      <%= render 'form' %>
      <%= link_to 'Back', ideas_path %>
    </div>
  </div>
  <hr />
  <br />
  <% @idea_responses.each do |idea_response| %>
    <div class="row">
    <div class="content-div col-md-8 col-md-offset-2">
      <%= render partial: 'idea_responses/idea_response', locals: {idea_response: idea_response} %>
    </div>
  </div>
  <br />
<% end %>

</div>
</div>

app/views/ideas/idea_wall.html.erb
<div class="container" ng-controller='ideasCtrl' ng-init="ideaAmmo = <%= current_user.ideaAmmo? ? current_user.ideaAmmo : 0 %>">
  <div class="row">
    <div class="padded col-md-2 col-md-offset-1 content-div">
      <i style="font-size:60pt" class="fa fa-lightbulb-o fa-6"></i>
      <h3>Idea Ammo: <span style="font-size:20pt;" class="badge">{{ideaAmmo}}</span></h3>
      <p>Idea ammo is used to gather feedback on your ideas</p>
    </div>
    <div class="padded col-md-3 col-md-offset-1 content-div">
      <i style="font-size:60pt" class="fa fa-bullhorn fa-6"></i>
      <p class="lead">Ready to earn idea ammo?</p>
      <p>Help others out by providing objective feedback on their startup ideas.</p>
      <%= link_to 'Give Feedback', new_idea_response_path, class: 'btn btn-primary btn-lg', style: 'color:white' %>
    </div>
    <div class="padded col-md-3 col-md-offset-1 content-div">
      <i style="font-size:60pt" class="fa fa-users fa-6"></i>
      <p class="lead">Want Feedback?</p>
      <p>Spend idea ammo to get feedback on your idea.</p>
      <%= link_to 'Create Idea', new_idea_path, class: 'btn btn-primary btn-lg', style: 'color:white', 'ng-disabled' => 'ideaAmmo == 0' %>
    </div>
  </div>
  <div class="row">
    <h2 class="sub-header">Latest Valid8or Startup Ideas</h2>
    <div class="table-responsive content-div col-md-12">
      <table class="table table-striped table-hover">
        <thead>
          <tr>
            <th>Ideas</th>
            <th>Idea Descriptions</th>
            <th>Responses</th>
            <th>Post Date</th>
          </tr>
        </thead>
        <tbody>
        <% if @ideas.count == 0 %>
          <tr>
          <td>
            <p class="lead">No ideas here yet. Click "Create Idea" to post your idea!.</p>
          </td>
        </tr>
      <% end %>
        <% @ideas.each do |idea| %>
          <tr onclick="window.location.href='<%=idea_path(idea)%>'" ng-controller='ideaCtrl' ng-init="ideaId = <%= idea.id %>; responseRequestsPending = <%= idea.responseRequestsPending %>;">
          <td>
            <%#= link_to idea do %>
              <h4><%= idea.title%></h4>
            <%# end %>
          </td>
          <td><%= truncate(idea.description) %></td>
          <td><span class="badge" style="font-size:20pt;"> <%= idea.getResponses().count %></span></td>
          <td><%= time_ago_in_words(idea.created_at) %> ago</td>
        </tr>
      <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>
<% if current_user.get_ideas().count == 0 and !cookies[:how_to_shown]%>
  <% cookies[:how_to_shown] = true %>
  <script>
    //$('#how_to_modal').modal()    
  </script>
<% end %>

app/views/ideas/index.html.erb
<div class="container" ng-controller='ideasCtrl' ng-init="ideaAmmo = <%= current_user.ideaAmmo? ? current_user.ideaAmmo : 0 %>">
  <div class="row">
    <div class="padded col-md-2 col-md-offset-1 content-div">
      <i style="font-size:60pt" class="fa fa-lightbulb-o fa-6"></i>
      <h3>Idea Ammo: <span style="font-size:20pt;" class="badge">{{ideaAmmo}}</span></h3>
      <p>Idea ammo is used to gather feedback on your ideas</p>
    </div>
    <div class="padded col-md-3 col-md-offset-1 content-div">
      <i style="font-size:60pt" class="fa fa-bullhorn fa-6"></i>
      <p class="lead">Ready to earn idea ammo?</p>
      <p>Help others out by providing objective feedback on their startup ideas.</p>
      <%= link_to 'Give Feedback', new_idea_response_path, class: 'btn btn-primary btn-lg', style: 'color:white' %>
    </div>
    <div class="padded col-md-3 col-md-offset-1 content-div">
      <i style="font-size:60pt" class="fa fa-users fa-6"></i>
      <p class="lead">Want Feedback?</p>
      <p>Spend idea ammo to get feedback on your idea.</p>
      <%= link_to 'Create Idea', new_idea_path, class: 'btn btn-primary btn-lg', style: 'color:white', 'ng-disabled' => 'ideaAmmo == 0' %>
    </div>
  </div>
  <div class="row">
    <h2 class="sub-header">My Startup Ideas</h2>
    <div class="table-responsive content-div col-md-12">
      <table class="table table-striped table-hover">
        <thead>
          <tr>
            <th>Ideas</th>
            <th>Edit</th>
            <th>Refund</th>
            <th>Requests Pending</th>
          </tr>
        </thead>
        <tbody>
        <% if @ideas.count == 0 %>
          <tr>
          <td>
            <p class="lead">No ideas here yet. Click "Give Feedback" to earn idea ammo, then try "Create Idea" to spend idea ammo to gather feedback.</p>
          </td>
        </tr>
      <% end %>
        <% @ideas.each do |idea| %>
          <tr onclick="window.location.href='<%=idea_path(idea)%>'" ng-controller='ideaCtrl' ng-init="ideaId = <%= idea.id %>; responseRequestsPending = <%= idea.responseRequestsPending %>;">
          <td>
             <%#= link_to idea do %>
              <h4><%= idea.title%></h4>
            <%# end %>
          </td>
          <!-- <td><%#= link_to 'Show', idea %></td> -->
          <td><%= link_to edit_idea_path(idea) do %>
            <i class="fa fa-edit fa-2x"></i>
          <% end %>
          </td>
          <td>
            <%= link_to idea, method: :delete, data: { confirm: 'Are you sure?' } do %>
              <i class="fa fa-trash fa-2x"></i>
          <% end %> 
          </td>
          <td><span class="badge" style="font-size:20pt;"> {{responseRequestsPending}}</span></td>
          <td><button class="btn btn-primary" ng-click='createResponseRequest()'>Request Feedback</button></td>
        </tr>
      <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/ideas/new.html.erb
<div class="container">
  <div class="row">
    <div class="content-div col-md-8 col-md-offset-2">
      <h1>New Startup Idea</h1>
      <div class="panel panel-info">
        <div class="panel-heading">Posting Guidelines</div>
        <div class="panel-body">
          <p>The best ideas clearly state the <b>pain or problem</b> that a certain demographic has, followed by a clear statement of a <b>solution.</b> </p> 
        </div>
      </div>
      <%= render 'form' %>
      <%= link_to 'Back', ideas_path %>
    </div>
  </div>
</div>

app/views/ideas/show.html.erb
<div class="container">
  <%= render partial: 'ideas/idea', layout: 'layouts/content' %>
  <hr />
  <br />
  <% @idea_responses.each do |idea_response| %>
    <div class="row">
    <div class="content-div col-md-8 col-md-offset-2">
      <%= render partial: 'idea_responses/idea_response', locals: {idea_response: idea_response} %>
    </div>
  </div>
  <br />
<% end %>
</div>
<%= link_to 'Back', ideas_path, class: 'btn btn-primary' %>