config/routes.rb
Rails.application.routes.draw do

  resources :idea_response_comments

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => 'users/registrations'}

  resources :response_requests

  root to: 'home#splash'

  get 'home/splash'
  get 'home/about'
  get 'home/contact'
  get 'error/needResponseRequests'

  resources :idea_responses

  resources :ideas
  get 'ideas/idea_wall'

end

app/models/response_request.rb
class ResponseRequest < ActiveRecord::Base
  def self.getFirstForThisUser(user)

    #Get ideas that this user has already commented on
    ideasUserHasAlreadyCommentedOn = IdeaResponse
    .select('ideaId')
    .where('userId = ?', user.id)
    .distinct

    #Get the first request that this user hasn't him/herself posted
    #and also ensure that they haven't already commented on it
    oldestResponseRequest = ResponseRequest
    .joins('INNER JOIN ideas ON response_requests.ideaId = ideas.id')
    .where('ideas.userId != ? AND ideas.id NOT IN (?) AND response_requests.in_progress = ?', user.id, ideasUserHasAlreadyCommentedOn, false)
    .first
  end
end

app/controllers/response_requests_controller.rb
class ResponseRequestsController < ApplicationController
  before_action :set_response_request, only: [:show, :edit, :update, :destroy]

  # GET /response_requests
  # GET /response_requests.json
  def index
    @response_requests = ResponseRequest.all
  end

  # GET /response_requests/1
  # GET /response_requests/1.json
  def show
  end

  # GET /response_requests/new
  def new
    @response_request = ResponseRequest.new
  end

  # GET /response_requests/1/edit
  def edit
  end

  # POST /response_requests
  # POST /response_requests.json
  def create
    @response_request = ResponseRequest.new(response_request_params)

    #determine current idea ammo for this user
    ideaAmmo = current_user.ideaAmmo? ? current_user.ideaAmmo : 0

    #if user has > 1 idea ammo, spend 1 idea ammo
    if ideaAmmo >= 1
      ideaAmmo -= 1
      current_user.ideaAmmo = ideaAmmo
      current_user.save
    else
      format.json { render json: @response_request.errors, status: :unprocessable_entity }
      return
    end

    respond_to do |format|
      if @response_request.save
        format.html { redirect_to @response_request, notice: 'Response request was successfully created.' }
        format.json { render :show, status: :created, location: @response_request }
      else
        format.html { render :new }
        format.json { render json: @response_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /response_requests/1
  # PATCH/PUT /response_requests/1.json
  def update
    respond_to do |format|
      if @response_request.update(response_request_params)
        format.html { redirect_to @response_request, notice: 'Response request was successfully updated.' }
        format.json { render :show, status: :ok, location: @response_request }
      else
        format.html { render :edit }
        format.json { render json: @response_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /response_requests/1
  # DELETE /response_requests/1.json
  def destroy
    @response_request.destroy
    respond_to do |format|
      format.html { redirect_to response_requests_url, notice: 'Response request was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_response_request
    @response_request = ResponseRequest.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def response_request_params
    params.require(:response_request).permit(:ideaId, :in_progress)
  end
end

app/helpers/response_requests_helper.rb
module ResponseRequestsHelper
end

app/views/response_requests/_form.html.erb
<%= form_for(@response_request) do |f| %>
  <% if @response_request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@response_request.errors.count, "error") %> prohibited this response_request from being saved:</h2>

      <ul>
      <% @response_request.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :ideaId %><br>
    <%= f.number_field :ideaId %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/response_requests/edit.html.erb
<h1>Editing response_request</h1>

<%= render 'form' %>

<%= link_to 'Show', @response_request %> |
<%= link_to 'Back', response_requests_path %>

app/views/response_requests/index.html.erb
<h1>Listing response_requests</h1>

<table>
  <thead>
    <tr>
      <th>Ideaid</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @response_requests.each do |response_request| %>
      <tr>
        <td><%= response_request.ideaId %></td>
        <td><%= link_to 'Show', response_request %></td>
        <td><%= link_to 'Edit', edit_response_request_path(response_request) %></td>
        <td><%= link_to 'Destroy', response_request, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Response request', new_response_request_path %>

app/views/response_requests/new.html.erb
<h1>New response_request</h1>

<%= render 'form' %>

<%= link_to 'Back', response_requests_path %>

app/views/response_requests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Ideaid:</strong>
  <%= @response_request.ideaId %>
</p>

<%= link_to 'Edit', edit_response_request_path(@response_request) %> |
<%= link_to 'Back', response_requests_path %>