config/routes.rb
Rails.application.routes.draw do

  resources :idea_response_comments

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => 'users/registrations'}

  resources :response_requests

  root to: 'home#splash'

  get 'home/splash'
  get 'home/about'
  get 'home/contact'
  get 'error/needResponseRequests'

  resources :idea_responses

  resources :ideas
  get 'ideas/idea_wall'

end

app/controllers/idea_responses_controller.rb
class IdeaResponsesController < ApplicationController
  before_action :set_idea_response, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_filter :only_allow_user, only: [:edit, :update, :destroy]

  def only_allow_user
    if current_user.id != @idea_response.userId
      redirect_to idea_responses_path
    end
  end

  # GET /idea_responses
  # GET /idea_responses.json
  def index
    @idea_responses = IdeaResponse.getResponsesByUser(current_user)
  end

  # GET /idea_responses/1
  # GET /idea_responses/1.json
  def show
    @idea = @idea_response.getIdea()
    @idea_response.comments = @idea_response.get_comments()
  end

  # GET /idea_responses/new
  def new
    @idea_response = IdeaResponse.new

    #Get oldest response request
    #ideaId of this response request is @idea_response.ideaId
    #Get idea, and all other responses sorted by time

    #Oldest request will have earliest primary key id
    @response_request = ResponseRequest.getFirstForThisUser(current_user)

    if !@response_request.nil?
      @ideaId = @response_request.ideaId
      @idea_response.ideaId = @ideaId
      @idea = Idea.find(@ideaId)
      @earlierResponses = @idea.getResponses()

      #set to in progress
      @response_request.in_progress = true
      @response_request.save
    else
      #No requests...give them a credit if they don't have one.
      current_user.addComplimentaryIdeaAmmoIfEmpty(current_user)
      redirect_to "/error/needResponseRequests"
    end
  end

  # GET /idea_responses/1/edit
  def edit
    @idea_response.comments = @idea_response.get_comments()
    @idea = @idea_response.getIdea()
  end

  # POST /idea_responses
  # POST /idea_responses.json
  def create
    @idea_response = IdeaResponse.new(idea_response_params)
    @idea_response.userId = current_user.id

    respond_to do |format|
      if @idea_response.save
        #format.html { redirect_to @idea_response, notice: 'Idea response was successfully created.' }
        format.html{redirect_to ideas_path, notice: 'Idea response was successfully created.' }

        format.json { render :show, status: :created, location: @idea_response }

        @idea_response.completeResponse(current_user)
      else
        format.html { render :new }
        format.json { render json: @idea_response.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /idea_responses/1
  # PATCH/PUT /idea_responses/1.json
  def update
    respond_to do |format|
      if @idea_response.update(idea_response_params)
        format.html { redirect_to @idea_response, notice: 'Idea response was successfully updated.' }
        format.json { render :show, status: :ok, location: @idea_response }
      else
        format.html { render :edit }
        format.json { render json: @idea_response.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /idea_responses/1
  # DELETE /idea_responses/1.json
  def destroy

    #destroy comments
    comments = @idea_response.get_comments()
    comments.each{|comment| comment.destroy}

    @idea_response.destroy
    respond_to do |format|
      format.html { redirect_to idea_responses_url, notice: 'Idea response was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_idea_response
    @idea_response = IdeaResponse.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def idea_response_params
    params.require(:idea_response).permit(:description, :userId, :ideaId)
  end
end

app/helpers/idea_responses_helper.rb
module IdeaResponsesHelper
end

app/views/idea_responses/_form.html.erb
<%= form_for(@idea_response, html: {'data-parsley-validate' => ''}) do |f| %>
  <div class="form-group">
  <% if @idea_response.errors.any? %>
    <div id="error_explanation">
    <h2><%= pluralize(@idea_response.errors.count, "error") %> prohibited this idea_response from being saved:</h2>

    <ul>
      <% @idea_response.errors.full_messages.each do |message| %>
        <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>
  <div class="field">
    <%= f.label 'My Feedback' %><a href='http://daringfireball.net/projects/markdown/syntax'> (You can use Markdown)</a><br>
    <%= f.text_area :description, 'data-parsley-validation-threshold' => "0", 'data-parsley-trigger' => "keyup", 'data-parsley-minlength' => 100, rows: 5, class: 'form-control' %>
  </div>

  <% if defined? @idea %>
    <%= hidden_field :idea_response, :ideaId %>
<% end %>

<div class="actions">
  <% if action_name == 'new' %>
    <%= f.submit "Give Feedback", class: 'btn btn-primary' %>
  <% else %>
    <%= f.submit "Update", class: 'btn btn-primary' %>
  <% end %>
  </div>
</div>
<% end %>

app/views/idea_responses/_idea_response.html.erb
<div ng-controller='ideaResponseCtrl' ng-init='ideaResponseId = <%= idea_response.id %>' >
  <p> Created <%= time_ago_in_words(idea_response.created_at) %> ago by user #<%=idea_response.userId%></p>

  <div style='text-align:left' class="well">
    <%= $markdown.render(idea_response.description).html_safe %>
  </div>

  <!-- Links -->
  <% if !(action_name == 'show' and controller_name == 'idea_responses') and idea_response.userId == current_user.id %>
    <%= link_to 'Details', idea_response, class:'btn btn-primary' %>
<% end %>

  <% if idea_response.userId == current_user.id %>
    <%= link_to 'Edit', edit_idea_response_path(idea_response), class:'btn btn-primary' %>
<% end %>
  <button class='btn btn-primary' ng-click="showNewCommentTextarea()">Add Comment</button>
  </p>

  <hr style="border-color:lightgrey; border-style:dashed;" />

  <!--Hidden textarea for comments-->
  <div ng-hide='!newCommentTextareaIsVisible'>
    <textarea class='form-control' id='new_comment_textarea' ng-model='newCommentDescription'></textarea>
    <br />
    <button class='btn btn-primary btn-xs' ng-click='createIdeaResponseComment()'>Add New Comment</button>
    <hr style="border-color:lightgrey; border-style:dashed;" />
  </div>


  <!--idea response comments-->
  <div id='ideaResponseCommentsDiv'>
    <% idea_response.comments.each do |idea_response_comment| %>
      <%= render partial: 'idea_response_comments/idea_response_comment', locals: {idea_response_comment: idea_response_comment} %>
    <hr style="border-color:lightgrey; border-style:dashed;" />
  <% end %>
  </div>

</div>

app/views/idea_responses/edit.html.erb
<h1>Editing Your Response:</h1>
<div class="container">
  <div class="row">
    <div class="content-div col-md-8 col-md-offset-2">
      <%= render 'ideas/idea' %>
    </div>
  </div>
  <hr />
  <div class="row">
    <div class="content-div col-md-8 col-md-offset-2">
      <%= render 'form' %>
    </div>
  </div>
  <br />
</div>
</div>

<%= link_to 'Back to Ideas', ideas_path, class: 'btn btn-primary ' %>

app/views/idea_responses/index.html.erb
<div class="container">
  <div class="row">
    <h2 class="sub-header">Feedback I've Given</h2>
    <div class="table-responsive content-div col-md-12">
      <table class="table table-striped table-hover">
        <thead>
          <tr>
            <th>Idea Responses</th>
            <th>Edit Response</th>
            <th>Delete Response</th>
            <th>Comments</th>
          </tr>
        </thead>
        <tbody>
        <% if @idea_responses.count == 0 %>
          <tr>
          <td>
            <p class="lead">You haven't given any feedback yet...Click <a href='/idea_responses/new'>here</a> to get started and earn some idea ammo.</p>
          </td>
        </tr>
      <% end %>
        <% @idea_responses.each do |idea_response| %>
          <tr>
          <td>
            <%= link_to idea_response do %>
              <h4>In response to: '<%= idea_response.idea.title %>'</h4>
          <% end %>
          </td>
          <!-- <td><%#= link_to 'Show', idea %></td> -->
          <td><%= link_to edit_idea_response_path(idea_response) do %>
            <i class="fa fa-edit fa-2x"></i>
          <% end %>
          </td>
          <td>
            <%= link_to idea_response, method: :delete, data: { confirm: 'Are you sure?' } do %>
              <i class="fa fa-trash fa-2x"></i>
          <% end %> 
          </td>
          <td><span class="badge" style="font-size:20pt;"> <%= idea_response.comments.count%><span></td>
        </tr>
      <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>
<br />
<%= link_to 'New Idea response', new_idea_response_path, class: 'btn btn-primary btn-lg' %>

app/views/idea_responses/new.html.erb
<div class="container">
  <div class="row">
    <div class="content-div col-md-8 col-md-offset-2">
      <%= render 'ideas/idea' %>
    </div>
  </div>
  <hr />
  <div class="row">
    <div ng-controller='newIdeaResponseCtrl' ng-init='response_request_id = <%= @response_request.id %>' class="content-div col-md-8 col-md-offset-2">
      <%= render 'form' %>
      <%= link_to 'Back to Ideas', ideas_path %>
    </div>
  </div>
  <br />
  <% @earlierResponses.each do |idea_response| %>
    <div class="row">
    <div class="content-div col-md-8 col-md-offset-2">
      <%= render partial: 'idea_responses/idea_response', locals: {idea_response: idea_response} %>
    </div>
  </div>
  <br />
<% end %>

</div>
</div>

app/views/idea_responses/show.html.erb
<div class="container">
  <%= render partial: 'ideas/idea', layout: 'layouts/content' %>
  <br />
  <%= render partial: 'idea_responses/idea_response', layout: 'layouts/content', locals: {idea_response: @idea_response} %>
  <br />
  <%= link_to 'Back to my Responses', idea_responses_path, class:'btn btn-primary'%>  
  <%= link_to 'Back to my Ideas', ideas_path, class:'btn btn-primary' %>
</div>