config/routes.rb
Rails.application.routes.draw do

  resources :idea_response_comments

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => 'users/registrations'}

  resources :response_requests

  root to: 'home#splash'

  get 'home/splash'
  get 'home/about'
  get 'home/contact'
  get 'error/needResponseRequests'

  resources :idea_responses

  resources :ideas
  get 'ideas/idea_wall'

end

app/models/idea_response_comment.rb
class IdeaResponseComment < ActiveRecord::Base
end

app/controllers/idea_response_comments_controller.rb
class IdeaResponseCommentsController < ApplicationController
  before_action :set_idea_response_comment, only: [:show, :edit, :update, :destroy]
  before_filter :only_allow_user, only: [:show, :edit, :update, :destroy]

  def only_allow_user
    if current_user.id != @idea_response_comment.user_id
      redirect_to idea_response_comments_path
    end
  end

  respond_to :html, :json

  def index
    @idea_response_comments = IdeaResponseComment.all
    respond_with(@idea_response_comments)
  end

  def show
    #respond_with(@idea_response_comment)
    render partial: 'idea_response_comments/idea_response_comment', locals: {idea_response_comment: @idea_response_comment}
  end

  def new
    @idea_response_comment = IdeaResponseComment.new
    respond_with(@idea_response_comment)
  end

  def edit
  end

  def create
    @idea_response_comment = IdeaResponseComment.new(idea_response_comment_params)
    @idea_response_comment.user_id = current_user.id
    @idea_response_comment.save
    respond_with(@idea_response_comment)
  end

  def update
    @idea_response_comment.update(idea_response_comment_params)
    respond_with(@idea_response_comment)
  end

  def destroy
    @idea_response_comment.destroy
    respond_with(@idea_response_comment)
  end

  private
  def set_idea_response_comment
    @idea_response_comment = IdeaResponseComment.find(params[:id])
  end

  def idea_response_comment_params
    params.require(:idea_response_comment).permit(:idea_response_id, :user_id, :description)
  end
end

app/helpers/idea_response_comments_helper.rb
module IdeaResponseCommentsHelper
end

app/views/idea_response_comments/_form.html.erb
<%= form_for(@idea_response_comment) do |f| %>
  <% if @idea_response_comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@idea_response_comment.errors.count, "error") %> prohibited this idea_response_comment from being saved:</h2>

      <ul>
      <% @idea_response_comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :idea_response_id %><br>
    <%= f.number_field :idea_response_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/idea_response_comments/_idea_response_comment.html.erb
<blockquote style='padding:0px;'>
  <p><%= idea_response_comment.description %></p>
  <footer>By user#<%= idea_response_comment.user_id %> <cite title="Creation Date"><%= time_ago_in_words(idea_response_comment.created_at) %> ago</cite></footer>
<% if idea_response_comment.user_id == current_user.id %>
  <%#= link_to 'Edit', edit_idea_response_comment_path(idea_response_comment), class:'btn btn-xs btn-primary' %>
<% end %>
</blockquote>

app/views/idea_response_comments/edit.html.erb
<h1>Editing idea_response_comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @idea_response_comment %> |
<%= link_to 'Back', idea_response_comments_path %>

app/views/idea_response_comments/index.html.erb
<h1>Listing idea_response_comments</h1>

<table>
  <thead>
    <tr>
      <th>Idea response</th>
      <th>User</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @idea_response_comments.each do |idea_response_comment| %>
      <tr>
        <td><%= idea_response_comment.idea_response_id %></td>
        <td><%= idea_response_comment.user_id %></td>
        <td><%= idea_response_comment.description %></td>
        <td><%= link_to 'Show', idea_response_comment %></td>
        <td><%= link_to 'Edit', edit_idea_response_comment_path(idea_response_comment) %></td>
        <td><%= link_to 'Destroy', idea_response_comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Idea response comment', new_idea_response_comment_path %>

app/views/idea_response_comments/new.html.erb
<h1>New idea_response_comment</h1>

<%= render 'form' %>

<%= link_to 'Back', idea_response_comments_path %>

app/views/idea_response_comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Idea response:</strong>
  <%= @idea_response_comment.idea_response_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @idea_response_comment.user_id %>
</p>

<p>
  <strong>Description:</strong>
  <%= @idea_response_comment.description %>
</p>

<%= link_to 'Edit', edit_idea_response_comment_path(@idea_response_comment) %> |
<%= link_to 'Back', idea_response_comments_path %>